import numpy as np

In [1]:
import numpy as np


In [2]:
list = [20,27,9,12,31, 17, 4, 50,39, 35]

In [3]:
arr = np.array(list)

In [4]:
print(arr * 4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023


In [6]:
min_index = np.argmin(arr)
print(min_index)

max_index = np.argmax(arr)
print(max_index)

6
7


In [7]:
print(arr[min_index])
print(arr[max_index])

#no they do not match the same as what was printed in the cell above.

4
50


In [8]:
values_over_twenty = arr[arr >20]
print(values_over_twenty)

[27 31 50 39 35]


In [10]:
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
print(matrix)

[[5, 12, 17, 9], [8, 21, 14, 3], [6, 13, 19, 11]]


In [11]:
arr = np.array(matrix)

print(arr.shape)

(3, 4)


In [12]:
# prints out three rows and 4 colums in shape


In [13]:
print(arr[:, 2])
print(arr[1])

print(arr * 2)

[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [15]:
print(arr.mean (axis = 0))

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [16]:
print(arr.mean())


11.5


In [17]:
print(arr.max(axis = 1))
print(arr.min(axis = 0))

[17 21 19]
[ 5 12 14  3]


In [19]:
flat = arr.flatten()
print(flat)
print(flat.shape)
#what happened to the shape is that teh array is no longer "2d" but now one
#full 1D element

[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)


In [20]:
flaten_min = np.argmin(flat)
flaten_max = np.argmax(flat)
print(flaten_min)
print(flaten_max)

7
5


In [22]:
flatmin_into_rc_column = np.unravel_index(flaten_min, arr.shape)
flatmax_into_rc_column = np.unravel_index(flaten_max, arr.shape)
print("min coordinates(row, col):", flatmin_into_rc_column)
print("max coordinates(row, col):", flatmax_into_rc_column)

min coordinates(row, col): (np.int64(1), np.int64(3))
max coordinates(row, col): (np.int64(1), np.int64(1))


In [23]:
over_fifteen = arr[arr >15]
print(over_fifteen)

[17 21 19]


In [24]:
sorted_rows = np.sort(arr, axis =1)
print(sorted_rows)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [25]:
## Prime star systems


In [36]:
arr = np.array([
    [2,3,5],
    [14,6,8],
    [11,13,17],
    [7,10,13]
])

def is_prime(n):
    if n < 2:
        return False 
    for i in range (2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def rows_with_prime(a):
    rows_list = []
    for row in a:
        has_prime = False
        for value in row:
            if is_prime(value):
                has_prime = True
                break
        if has_prime: 
            rows_list.append(row)
    return np.array(rows_list)

result = rows_with_prime(arr)
print(result)

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [37]:
def checkerboard():
    board = np.zeros((8,8), dtype = int)
    for i in range(8):
        for j in range(8):
            if (i+j)%2 ==0:
                board[i,j] = 1
    return board
def reverse_checkerboard():
    board = np.zeros((8,8), dtype = int)
    for i in range(8):
        for j in range(8):
            if (i+j)%2 ==1:
                board[i, j] = 1
    return board
print("checkerboard():")
print (checkerboard())
print()
print("reverse_checkerboard()")
print(reverse_checkerboard())
print()

checkerboard():
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

reverse_checkerboard()
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]



In [39]:

def expansion(arr, num_spaces):
    result_list = []
    spaces = " " * num_spaces
    for word in arr:
        chars = [c for c in word]      
        expanded = spaces.join(chars) def secondDimmest(stars):
    second_list = []
    for row in stars:
        sorted_row = np.sort(row)    # ascending
        second_brightest = sorted_row[-2]  # second largest
        second_list.append(second_brightest)
    return np.array(second_list)
        result_list.append(expanded)
    return np.array(result_list)

universe = np.array(["galaxy", "clusters"])
print("expansion(universe, 1):")
print(expansion(universe, 1))
print()
print("expansion(universe, 2):")
print(expansion(universe, 2))

def secondDimmest(stars):
    second_list = []
    for row in stars:
        sorted_row = np.sort(row)    
        second_brightest = sorted_row[-2]  
        second_list.append(second_brightest)
    return np.array(second_list)
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print("stars array:")
print(stars)
print()
print("secondDimmest(stars):")
print(secondDimmest(stars))


expansion(universe, 1):
['g a l a x y' 'c l u s t e r s']

expansion(universe, 2):
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']
stars array:
[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]

secondDimmest(stars):
[1889 1647 1138 1863 1592]


In [41]:
def secondDimmest(stars):
    second_list = []
    for row in stars:
        sorted_row = np.sort(row)  
        second_brightest = sorted_row[-2] 
        second_list.append(second_brightest)
    return np.array(second_list)

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print("stars array:")
print(stars)
print()
print("secondDimmest(stars):")
print(secondDimmest(stars))

stars array:
[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]

secondDimmest(stars):
[1889 1647 1138 1863 1592]
